all: tcp_server tcp_client
	
tcp_server :tcp_server_select_oddeven.c
	gcc -o tcp_server tcp_server_select_oddeven.c

tcp_client :tcp_client_select_oddeven.c
	gcc -o tcp_client tcp_client_select_oddeven.c
